//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookedTrips> BookedTrips { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentSites> EquipmentSites { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<TripSite> TripSite { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
    }
}
