//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tripsDbEntities1 : DbContext
    {
        public tripsDbEntities1()
            : base("name=tripsDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookedTrip> BookedTrips { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentSite> EquipmentSites { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripSite> TripSites { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
