//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sites()
        {
            this.EquipmentSites = new HashSet<EquipmentSites>();
            this.TripSite = new HashSet<TripSite>();
        }
    
        public int CodeSite { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public string AddressGMaps { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public System.TimeSpan OpeningHour { get; set; }
        public System.TimeSpan ClosingHour { get; set; }
        public string Category { get; set; }
        public Nullable<System.TimeSpan> EstimatedStay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSites> EquipmentSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripSite> TripSite { get; set; }
    }
}
