//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripSite
    {
        public int TripSiteId { get; set; }
        public int SiteId { get; set; }
        public int TripId { get; set; }
        public int OrderInTrip { get; set; }
    
        public virtual Sites Sites { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
